version: "2"

services:

  php:
    image: "zeroboh/php:7.0-fpm-alpine"
    links:
      - "mariadb"
      - "redis"
    volumes:
      - "/d/Docker/billardcafe-neos:/data/"

  nginx:
    image: "zeroboh/nginx:1.11-alpine"
    ports:
      - "32831:32831"
    links:
      - "php"
    volumes:
      - "/d/Docker/billardcafe-neos:/data/"
      - "/d/Docker/billardcafe-neos/Configuration/Docker/default.conf:/etc/nginx/conf.d/default.conf"
    environment:
      FLOW_PATH_TEMPORARY_BASE: "/tmp"

  redis:
     image: "zeroboh/redis:3.2-alpine"

  mariadb:
    image: "zeroboh/mariadb:10.1-debian-jessie"
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: "neos"
      MYSQL_DATABASE: "neos"
      MYSQL_USER: "neos"
      MYSQL_PASSWORD: "neos"
