
Neos:
  Imagine:
    driver: Imagick
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: neos
        user: neos
        password: neos
        host: neos3-mariadb
      doctrine:
        sqlLogger: Neos\Flow\Persistence\Doctrine\Logging\SqlLogger
  SwiftMailer:
    transport:
      type: Swift_SmtpTransport
      options:
        host: mail
        port: 1025
Jonnitto:
  GoogleMaps:
    APIKey: AIzaSyCczl0glbOz-k9NJ1yiBiBzzYqdr-dAq4Q
    SigningSecret: PNKxkoI5gQPTW0WoaxA8EjlEBnw=
    includeGoogleAPI: false
    includeFunction: false
    includeBackendJS: false
    includeCSS: false
    googleAPI: '//maps.google.com/maps/api/js?key={APIKey}&callback=initJonnittoGoogleMaps'
    googleStaticMapsAPI: '//maps.googleapis.com/maps/api/staticmap?key={APIKey}'
    cssClasses:
      container: false
      map: jonnitto-googlemaps-mapview
      streetview: jonnitto-googlemaps-streetview
      both:
        wrapper: jonnitto-googlemaps-both-wrapper
        map: jonnitto-googlemaps-both-mapview
        streetview: jonnitto-googlemaps-both-streetview
